sync new files

diff --git a/.local/bin/git-export b/.local/bin/git-export
--- a/.local/bin/git-export
+++ b/.local/bin/git-export
@@ -1,8 +1,25 @@
 #!/bin/env bash
 # Description: Git commit browser to export a commit into a zip archive
 
+usage() {
+    cat <<EOF
+`basename $0` is a git commit browser to export a selected commit into a zip archive.
+
+Usage: `basename $0`
+
+The script could be called from any directory in the repository. Only the files in the
+current directory and the parent directories get exported to the zip archive.
+EOF
+    exit $1
+}
+
+error() {
+    echo -e "\033[0;31mERROR:\033[0m $1\n"
+    usage 1
+}
+
 git_export() {
-    git status >/dev/null 2>&1 || return
+    git status >/dev/null 2>&1 || error "this is not a git repository"
     commitHash=$(git log --graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" | \
         fzf --ansi --no-sort --reverse --tiebreak=index --preview="f() { set -- \$(echo -- \$@ | grep -o '[a-f0-9]\{7\}'); [ \$# -eq 0 ] || git show --color=always \$1; }; f {}" | grep -o '[a-f0-9]\{7\}')
     [ -z "$commitHash" ] && exit
@@ -10,4 +27,6 @@ git_export() {
     git archive --format zip --output "$commitHash.zip" $commitHash
 }
 
+[ "$1" = "-h" ] && usage 0
+[ "$1" = "-help" ] && usage 0
 git_export
diff --git a/.local/bin/git-submodule-remove b/.local/bin/git-submodule-remove
--- a/.local/bin/git-submodule-remove
+++ b/.local/bin/git-submodule-remove
@@ -1,11 +1,30 @@
 #!/bin/sh
 # Description: function to remove a git submodule
 
-[ ! -d .git ] && echo "no git root directory" && exit
-[ ! -f .gitmodules ] && echo ".gitmodules not exist" && exit
+usage() {
+    cat <<EOF
+`basename $0` is a script to remove a git submodule.
+
+Usage: `basename $0` [GIT_SUBMODULE_PATH]
+
+The script must be called in the root directory of the git repository which
+contains the .git directory and the .gitmodules file.
+EOF
+    exit $1
+}
+
+error() {
+    echo -e "\033[0;31mERROR:\033[0m $1\n"
+    usage 1
+}
+
+[ "$1" = "-h" ] && usage 0
+[ "$1" = "-help" ] && usage 0
+[ ! -d .git ] && error "not in the git repository root directory"
+[ ! -f .gitmodules ] && error ".gitmodules do not exist"
 submodulPath="$@"
-[ -z "$submodulPath" ] && echo "submodul path not exist" && exit
-[ ! -d "$submodulPath" ] && echo "submodul path not exist" && exit
+[ -z "$submodulPath" ] && error "submodul path not exist"
+[ ! -d "$submodulPath" ] && error "submodul path not exist"
 grep "path = $submodulPath" .gitmodules >/dev/null || exit
 git submodule deinit -f "$submodulPath"
 rm -rf ".git/modules/${submodulPath}"
